# Generated by Django 5.0.2 on 2024-02-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Writer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
